# Numpy Data Journey

## 🚀 Quick Start

### Import

In [1]:
import numpy as np

## 💻 Basic Usage Examples

### Creating Arrays

#### Creating Arrays from Existing Data

In [2]:
Liste=[1,2,3]
Tab=np.array(Liste)
Tab

array([1, 2, 3])

#### Creating Pre-initialized Arrays

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Array Dimensions and Size

In [7]:
Tab.shape

(3,)

In [8]:
Tab.ndim

1

In [9]:
Tab.size

3

### Manipulate Array

#### Array Stacking Operations

In [10]:
Tab1=np.ones((3, 3))

In [11]:
Tab2=np.eye(3)

In [12]:
print("Le tableau numéro 1 est \n",Tab1)

Le tableau numéro 1 est 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print("Le tableau numéro 2 est \n", Tab2)

Le tableau numéro 2 est 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
Tab3=np.hstack((Tab1,Tab2))
Tab3

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1.]])

In [15]:
Tab4=np.vstack((Tab1,Tab2))

#### Array Reshaping Operations

In [19]:
Tab3=Tab3.reshape((6,3))
Tab3

array([[1., 1., 1.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 1., 0.],
       [1., 1., 1.],
       [0., 0., 1.]])

In [29]:
Tab=Tab.reshape(1,3)

In [30]:
Tab.shape

(1, 3)

In [33]:
Tab=Tab.squeeze()

In [34]:
Tab.shape

(3,)

In [36]:
Tab3.ravel()

array([1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       1.])