# Numpy Data Journey 

## 🚀 Quick Start


### Installation

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Import

In [2]:
import numpy as np

## 💻 Basic Usage Examples


### Creating Arrays

#### Creating Arrays from Existing Data

In [5]:
Liste=[1,2,3]
Table=np.array(Liste)
print("Le tableau est \n", Table)

Le tableau est 
 [1 2 3]


#### Creating Pre-initialized Arrays

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Array Dimensions and Size

In [13]:
Table.shape

(3,)

In [14]:
Table.ndim

1

In [15]:
Table.size

3

### Manipulate Arrays